disable docker build to run fast

diff --git a/.github/workflows/docker_release.yml b/.github/workflows/docker_release.yml
--- a/.github/workflows/docker_release.yml
+++ b/.github/workflows/docker_release.yml
@@ -18,52 +18,56 @@ jobs:
     # if: github.repository_owner == 'deepset-ai'
 
     steps:
-      - name: Checkout
-        uses: actions/checkout@v5
 
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v3
+      - name: Placeholder
+        run: echo "Placeholder"
 
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
+      # - name: Checkout
+      #   uses: actions/checkout@v5
 
-      # - name: Login to DockerHub
-      #   uses: docker/login-action@v3
+      # - name: Set up QEMU
+      #   uses: docker/setup-qemu-action@v3
+
+      # - name: Set up Docker Buildx
+      #   uses: docker/setup-buildx-action@v3
+
+      # # - name: Login to DockerHub
+      # #   uses: docker/login-action@v3
+      # #   with:
+      # #     username: ${{ secrets.DOCKER_HUB_USER }}
+      # #     password: ${{ secrets.DOCKER_HUB_TOKEN }}
+
+      # - name: Docker meta
+      #   id: meta
+      #   uses: docker/metadata-action@v5
       #   with:
-      #     username: ${{ secrets.DOCKER_HUB_USER }}
-      #     password: ${{ secrets.DOCKER_HUB_TOKEN }}
+      #     images: $DOCKER_REPO_NAME
 
-      - name: Docker meta
-        id: meta
-        uses: docker/metadata-action@v5
-        with:
-          images: $DOCKER_REPO_NAME
+      # - name: Build base images
+      #   uses: docker/bake-action@v5
+      #   env:
+      #     IMAGE_TAG_SUFFIX: ${{ steps.meta.outputs.version }}
+      #     HAYSTACK_VERSION: ${{ steps.meta.outputs.version }}
+      #   with:
+      #     workdir: docker
+      #     targets: base
+      #     push: false
 
-      - name: Build base images
-        uses: docker/bake-action@v5
-        env:
-          IMAGE_TAG_SUFFIX: ${{ steps.meta.outputs.version }}
-          HAYSTACK_VERSION: ${{ steps.meta.outputs.version }}
-        with:
-          workdir: docker
-          targets: base
-          push: false
+      # - name: Test base image
+      #   run: |
+      #     EXPECTED_VERSION=$(cat VERSION.txt)
+      #     if [[ $EXPECTED_VERSION == *"-"* ]]; then
+      #       EXPECTED_VERSION=$(cut -d '-' -f 1 < VERSION.txt)$(cut -d '-' -f 2 < VERSION.txt)
+      #     fi
+      #     TAG="base-${{ steps.meta.outputs.version }}"
 
-      - name: Test base image
-        run: |
-          EXPECTED_VERSION=$(cat VERSION.txt)
-          if [[ $EXPECTED_VERSION == *"-"* ]]; then
-            EXPECTED_VERSION=$(cut -d '-' -f 1 < VERSION.txt)$(cut -d '-' -f 2 < VERSION.txt)
-          fi
-          TAG="base-${{ steps.meta.outputs.version }}"
+      #     PLATFORM="linux/amd64"
+      #     VERSION=$(docker run --platform "$PLATFORM" --rm "deepset/haystack:$TAG" python -c"from haystack.version import __version__; print(__version__)")
+      #     [[ "$VERSION" = "$EXPECTED_VERSION" ]] || echo "::error 'Haystack version in deepset/haystack:$TAG image for $PLATFORM is different from expected'"
 
-          PLATFORM="linux/amd64"
-          VERSION=$(docker run --platform "$PLATFORM" --rm "deepset/haystack:$TAG" python -c"from haystack.version import __version__; print(__version__)")
-          [[ "$VERSION" = "$EXPECTED_VERSION" ]] || echo "::error 'Haystack version in deepset/haystack:$TAG image for $PLATFORM is different from expected'"
+      #     PLATFORM="linux/arm64"
+      #     VERSION=$(docker run --platform "$PLATFORM" --rm "deepset/haystack:$TAG" python -c"from haystack.version import __version__; print(__version__)")
+      #     [[ "$VERSION" = "$EXPECTED_VERSION" ]] || echo "::error 'Haystack version in deepset/haystack:$TAG image for $PLATFORM is different from expected'"
 
-          PLATFORM="linux/arm64"
-          VERSION=$(docker run --platform "$PLATFORM" --rm "deepset/haystack:$TAG" python -c"from haystack.version import __version__; print(__version__)")
-          [[ "$VERSION" = "$EXPECTED_VERSION" ]] || echo "::error 'Haystack version in deepset/haystack:$TAG image for $PLATFORM is different from expected'"
-
-          # Remove image after test to avoid filling the GitHub runner and prevent its failure
-          docker rmi "deepset/haystack:$TAG"
+      #     # Remove image after test to avoid filling the GitHub runner and prevent its failure
+      #     docker rmi "deepset/haystack:$TAG"
