don't send events to datadog

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -317,25 +317,25 @@ jobs:
             echo "alert_type=error" >> "$GITHUB_OUTPUT";
           fi
 
-      - name: Send event to Datadog
-        if: (success() || failure()) && github.ref_name == 'main'
-        uses: masci/datadog@v1
-        with:
-          api-key: ${{ secrets.CORE_DATADOG_API_KEY }}
-          api-url: https://api.datadoghq.eu
-          events: |
-            - title: "${{ github.workflow }} workflow"
-              text: "Job ${{ github.job }} in branch ${{ github.ref_name }}"
-              alert_type: "${{ steps.calculator.outputs.alert_type }}"
-              source_type_name: "Github"
-              host: ${{ github.repository_owner }}
-              tags:
-                - "project:${{ github.repository }}"
-                - "job:${{ github.job }}"
-                - "run_id:${{ github.run_id }}"
-                - "workflow:${{ github.workflow }}"
-                - "branch:${{ github.ref_name }}"
-                - "url:https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
+      # - name: Send event to Datadog
+      #   if: (success() || failure()) && github.ref_name == 'main'
+      #   uses: masci/datadog@v1
+      #   with:
+      #     api-key: ${{ secrets.CORE_DATADOG_API_KEY }}
+      #     api-url: https://api.datadoghq.eu
+      #     events: |
+      #       - title: "${{ github.workflow }} workflow"
+      #         text: "Job ${{ github.job }} in branch ${{ github.ref_name }}"
+      #         alert_type: "${{ steps.calculator.outputs.alert_type }}"
+      #         source_type_name: "Github"
+      #         host: ${{ github.repository_owner }}
+      #         tags:
+      #           - "project:${{ github.repository }}"
+      #           - "job:${{ github.job }}"
+      #           - "run_id:${{ github.run_id }}"
+      #           - "workflow:${{ github.workflow }}"
+      #           - "branch:${{ github.ref_name }}"
+      #           - "url:https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
 
   # integration-tests-macos:
   #   name: Integration / macos-latest
